server:
  port: 8989
spring:
  application:
    name: CLOUD-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri : forward:/orderFallBack

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/pay/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri : forward:/paymentFallBack


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#Hystrix Configuration
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
